Belleza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
]

blog/urls.py
from django.urls import path

from django.views.generic import TemplateView

from .views import *

app_name = 'blog'


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html')),
    path('', listar_publicaciones, name='listar_publicaciones'),
    path('<uuid:pub>/', ver_publicacion, name='ver_publicacion'),
    path('categoria/<int:categoria/', ver_publicaciones_categoria, name='ver_publicaciones_categoria')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

import uuid


class Categoria(models.Model):
    descripcion = models.CharField(max_length=60,
                                    help_text='Descripcion de la Categorira')
    autor = models.ForeignKey(User,
                                 on_delete=models.PROTECT,
                                 help_text='Seleccione el autor de la categoria')
    
    def __str__(self):
        return self.descripcion 


class Publicacion(models.Model):
    id= models.UUIDField(primary_key= True, editable=False, default=uuid.uuid4)
    titulo = models.CharField(max_length=200,
                                help_text='Escriba el titulo de la publicacion')
    contenido = models.TextField(max_length=20000,
                                help_text='Seleccions el autor de la categoria')
    f_pub = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicacion')
    categorias = models.ManyToManyField(Categoria,
                                        help_text='Seleccione las categorias')

    def __str__(self):
        return self.titulo

blog/views.py
from django.shortcuts import render

from .models import *


def listar_publicaciones(request):
    news = Publicacion.objects.all()
    return render(request, './post/index.html', {'news':news} )


def ver_publicacion(request, pub):
    publicacion = Publicacion.objects.get(id = pub)
    return render(request, './ver.html', {'pub':publicacion})


def ver_publicaciones_categoria(request, categoria):
    categoria = Categoria.objects.get(id = id(categoria))
    return render(request,'./post/index.html.html', {'categoria':categoria})

blog/templates/home.html
{% extends 'base.html' %}

{% block titulo %}Woman's Fashion{% endblock %}

{% block cuerpo %
        {% if categoria %}
            <h1 align="center" class="card-panel cyan darken-4 white text hoverable">Set MakeOver {{ categoria.descripcion }}
            </h1>
                {% for new in categoria.publicacion_set.all %}
                    <div>
                        <a href="{% url 'blog:ver_publicacion' new.id %}">
                            <h2 align="center" class="black-text">{{ new.titulo }}</h2>
                        </a>
                    </div>
                    <div align="center">
                        {{ new.contenido|truncatechars:250 }} <br>
                        <img class="responsive-img" src=" {{ new.imagen.url }} " height="10000">
                    </div>
                    <hr size="100" color="black">
            {% endfor %}
        {% endif %}           


<!DOCTYPE html>
<html lang="es">


   <head>
      <!--Compiled and minifield CCS-->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
      <img src="https://scontent.ftgu2-2.fna.fbcdn.net/v/t1.0-9/120428797_803425717085483_1356235267149845950_o.jpg?_nc_cat=103&_nc_sid=730e14&_nc_ohc=a7EZNg2FCyQAX-5kjWQ&_nc_ht=scontent.ftgu2-2.fna&oh=915383bf7898ae1ec319ad43b0eb766d&oe=5F972F1E" 
      alt="Blog de belleza :: The Beauty Blog " data-at2x="https://scontent.ftgu2-2.fna.fbcdn.net/v/t1.0-9/120428797_803425717085483_1356235267149845950_o.jpg?_nc_cat=103&_nc_sid=730e14&_nc_ohc=a7EZNg2FCyQAX-5kjWQ&_nc_ht=scontent.ftgu2-2.fna&oh=915383bf7898ae1ec319ad43b0eb766d&oe=5F972F1E" 
      width="1010" height="200">
      <nav>
        <div class='nav-wrapper black'>
           <a href="{% url 'blog:listar_publicaciones' %}" class='brand-logo'>Woman's Fashion</a>

            <a href='#' data-target="menu-chico" class="sidenav-trigger"><i class='material-icons'>menu</i></a>

           <ul id='nav-mobile' class='right hide-on-med-and-down'>
              <li><a href="{% url 'blog:listar_publicaciones' %}">Maquillaje</a></li>    
              <li><a href="{% url 'blog:listar_publicaciones' %}">Cabello</a></li>
              <li><a href="{% url 'blog:listar_publicaciones' %}">Cremas</a></li>
              <li><a href="{% url 'blog:listar_publicaciones' %}">Cuerpo</a></li>
           </ul>
        </div>

        <ul class='sidenav' id='menu-chico'>
         <li><a href="{% url 'blog:listar_publicaciones' %}">Maquillaje</a></li>    
         <li><a href="{% url 'blog:listar_publicaciones' %}">Cabello</a></li>
         <li><a href="{% url 'blog:listar_publicaciones' %}">Cremas</a></li>
         <li><a href="{% url 'blog:listar_publicaciones' %}">Cuerpo</a></li>
        </ul>

     </nav>        <h2><a href="http://belletica.com/blog/set-de-maquillaje-low-cost/">Set de maquillaje low cost: los productos más asequibles para todos los bolsillos</a></h2>

    
        <p class="post-meta">Creado por <a href="http://belletica.com/blog/author/ajimenez/" title="Creados por Nicolth" rel="author">Nicolth</a></p>					<p>¡Hola! ¿Qué tal estáis? Volvemos una semana más, esta vez para hacer un post especial. Hoy no vamos a hablar de ninguna técnica nueva, sino que vamos a llenar tu set de maquillaje al completo por menos de 3o euros. ¿Te gusta la idea? Encontrarás tres opciones diferentes, que dependerán del presupuesto final que tengas. ¡Sigue leyendo! &nbsp; Set de maquillaje básico por menos de 10 euros No hace falta tener un gran presupuesto para ir...</p>						
    </div>
      <body background="https://i.pinimg.com/736x/15/19/6f/15196f27bb44d99b94e99d8c6b89db0d.jpg"></body>
      <div align="center"><img src="https://i.ebayimg.com/thumbs/images/g/NyoAAOSwmphaTFgz/s-l225.jpg"
         width="300" height="300"></div>
       <div class='container' style='padding-bottom:2em' >

       {% block cuerpo %}
           
       <div align="center">Paleta de maquillaje Miss Rose</div>     

       {% endblock %}

      </div>

       <script>
         document.addEventListener('DOMContentLoaded', function() {
             var elems = document.querySelectorAll('.carousel');
             var instances = M.carousel-darkinit(elems, options);
          });
    
          // Or with jQuery
    
          $(document).ready(function(){
             $('.carousel').carousel();
          });         
          
       </script>         


      </div>

      <footer class='pago-footer black white-text'>
         <div aling='center' style='padding:2em'>
             Woman's Fashion © Todos los derechos reservados
         </div>
      </footer>
  </body>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
   <!--AddToAny BEGIN-->
   <script async src="https://static.addtoany.com/menu/page.js"></script>
   <!--AddToAny END-->      

   </body>
</html>
           

blog/templates/post/index.html
{% extends 'base.html' %}

{% block cuerpo %}
    {% if categoria %}
        <h1>Publicaciones en {{ categoria.descripcion }}</h1>
        {% for new in categoria.publicacion_set.all %}
            <div>
                <h1><a href="{% url 'blog:ver_publicacion' new.id %}">{{new.titulo}}</a><br>
                <p>
                    {{ new.contenido|truncatechars:250 }} <br>
                    {{ new.autor.get_full_name }} publicado: {{ new.f_pub }}
                    {% for new in categoria.publicacion_set.all %}
                        <a href="{% url 'blog:ver_publicacion_categoria' categoria.id %}">{{ categoria.descripcion }}<a> 
                    {% endfor %}
                </p>
            </div>
            {% endfor %}

        {% else %}
            
            {% for new in news %}
                <div>
                    <h2><a href=" {% url 'blog:ver_publicacion' new.id %}">{{ new.titulo }}</a></h2> <br>
                    <p>
                        {{ new.contenido|truncatechars:250 }} <br>
                        {{ new.autor.get_full_name }} publicacion; {{ new.f_pub }}

                        {% for categoria in new.categoria %}
                            <a href="{% url blog:ver_publicacion_categoria' categoria.id}">{{ categoria.descripcion }}</a>
                        {% endfor %}

                    </p>
                </div>
            {% endfor %}
        {% endif %}
           
{% endblock %}

blog/templates/ver.html
{% extends 'base.html' %}

{% block cuerpo %} {{ pub.titulo|truncatechars:30 }} | NY Times {% endblock %}

{% block cuerpo %}

    <h1> {{ pub.titulo }} </h1>
    <p aling='justify'>
        {{ pub.contenido }} 
    </p>
    {{ new.autor.gey_full_name }} publicado: {{ new.f_pub }}

    <div class='aZa_kit aZa_kit_site_32 aZa_default_style'>
        <a class='aZa_buttom_facebook'></a>
        <a class='aZa_buttom_twitter'></a>
        <a class='aZa_buttom_email'></a>
        <a class='aZa_buttom_whatsapp'></a>
        <a class='aZa_buttom_line'></a>
        <a class='aZa_buttom_copy_link'></a>
    </div>
{% endblock %}